[package]
name = "advent23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "./util" }

[[bin]]
name = "01a"
path = "src/01/a.rs"

[[bin]]
name = "01b"
path = "src/01/b.rs"

[[bin]]
name = "02a"
path = "src/02/a.rs"

[[bin]]
name = "02b"
path = "src/02/b.rs"

[[bin]]
name = "03a"
path = "src/03/a.rs"

[[bin]]
name = "03b"
path = "src/03/b.rs"

[workspace]

members = [
    "util",
]